### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by meeech** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#12]
Hi @kostis-codefresh & @PhilippPlotnikov 

Just wanted to make you were aware of https://github.com/argoproj/argo-rollouts/issues/2720

We are updating the naming convention for plugins for rollouts. 

So in your case, the repo would need to move to rollouts-plugin-trafficrouter-gatewayapi

I hope this isn't too much of an inconvenience.

**Comment by kostis-codefresh** [comment]
@meeech Fine by me. I don't have the required privileges to do this myself

@zachaller feel free to rename the repo.

**Comment by zachaller** [comment]
Interesting I would have thought you had permission to do that, I have renamed it but you might also want to update go mod and import statements

**Comment by kostis-codefresh** [comment]
Solved by https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/pull/13
