### ISSUE TITLE
Failed to run Gateway API plugin

### ISSUE THREAD

**Issue by komalsukhani** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#29]
I have installed the latest version of the argo-rollout controller and v0.0.1 gateway API plugin.
I have installed plugin using ConfigMap as follows
```bash
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
  name: argo-rollouts-config
data:
  trafficRouterPlugins: |-
    - name: "argoproj-labs/gatewayAPI"
      location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.0.1/gateway-api-plugin-darwin-arm64"
```

Plugin is getting downloaded successfully but when I create a rollout I get the below error:
```
failed to get traffic router plugin argoproj-labs/gatewayAPI: unable to start plugin system: unable to get plugin client (argoproj-labs/gatewayAPI) for ping: exec: Stdout already set\n" error="<nil>"
```

**Comment by kolobych** [comment]
I had the same problem. After narrowing down the issue, I figured out that it's necessary to restart the Argo Rollouts controller to get the plugin up and running.
@komalsukhani, run `kubectl rollout restart deployment -n argo-rollouts argo-rollouts` to restart the controller. 
I've made a PR to update the documentation and address this oversight.

**Comment by Philipp-Plotnikov** [comment]
@kolobych I understood that you know the issue, can you explain it ? It is the problem of argo-rollouts controller side or of plugin ? Was it fixed ? Does it work now ?

**Comment by Philipp-Plotnikov** [comment]
@kolobych I have seen your PR

**Comment by lolhax1337** [comment]
Same here. Plugin versions 0.2.0 and 0.3.0 -> CM mounted, after `kubectl rollout restart deployment -n argo-rollouts argo-rollouts` on new pods:

```
time="2024-07-01T14:46:38Z" level=info msg="Argo Rollouts starting" version=v1.7.0+6937996
time="2024-07-01T14:46:38Z" level=info msg="Creating event broadcaster"
2024-07-01T14:46:38.975517525Z time="2024-07-01T14:46:38Z" level=info msg="Setting up event handlers"
2024-07-01T14:46:38.975524925Z time="2024-07-01T14:46:38Z" level=info msg="Setting up experiments event handlers"
2024-07-01T14:46:38.975589514Z time="2024-07-01T14:46:38Z" level=info msg="Setting up analysis event handlers"
2024-07-01T14:46:38.979223324Z time="2024-07-01T14:46:38Z" level=fatal msg="Failed to download plugins: failed to create plugin folder for plugin (argoproj-labs/gatewayAPI): (mkdir /home/argo-rollouts/plugin-bin: read-only file system)"
```

**Comment by FredrikAugust** [comment]
I'm running into this issue now while trying to run a custom build in my cluster. It says 

```
time="2024-08-30T12:04:45Z" level=info msg="Started syncing rollout" generation=1229 namespace=init resourceVersion=412081617 rollout=init-messaging
time="2024-08-30T12:04:45Z" level=info msg="delaying service switch from  to 68f4dfbdbd: ReplicaSet has zero availability" namespace=init rollout=init-messaging service=messaging-canary
time="2024-08-30T12:04:45Z" level=error msg="roCtx.reconcile err failed to get traffic router plugin argoproj-labs/gatewayAPI: unable to start plugin system: unable to get plugin client (argoproj-labs/gatewayAPI) for ping: exec: Stdout already set" generation=1229
```

**Comment by Philipp-Plotnikov** [comment]
Did you create build for needing os ?
I have mac, so I need to create build for Linux and run it on node in cluster

**Comment by FredrikAugust** [comment]
Yep, I'm running the linux-amd64 build in my cluster

**Comment by FredrikAugust** [comment]
It also downloads successfully:

```
│ time="2024-08-30T12:22:27Z" level=info msg="Downloading plugin argoproj-labs/gatewayAPI from: **********/gatewayapi-plugin-linux-amd64"                                                                                   │
│ time="2024-08-30T12:22:28Z" level=info msg="Download complete, it took 1.092799879s"                                                                                                                                                                                           │
```

**Comment by Philipp-Plotnikov** [comment]
I have this error only in 2 cases:
1. Incompatible build(I tried to run arm on amd)
2. When I run Argo Rollouts from IDEA with plugin. And when I stop Argo Rollouts it sometimes doesn't kill plugin process so I need to kill it manually.

**Comment by Philipp-Plotnikov** [comment]
@FredrikAugust you are launching controller locally with access to cluster or in cluster itself ? Previous plugin process was killed successfully ?

**Comment by FredrikAugust** [comment]
I'm running it by passing the following helm chart values:

```yaml
        controller:
          trafficRouterPlugins:
            trafficRouterPlugins: |-
              - name: "argoproj-labs/gatewayAPI"
                location: "**********/gatewayapi-plugin-linux-amd64"
```

**Comment by FredrikAugust** [comment]
I'm now seeing that both `dist` builds for linux appear to be ARM if I'm reading this right

```
gatewayapi-plugin-linux-amd64:            ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=1khFSbvEwTxvaSKR3Fda/a3QqGzCI_mM8kWyjxpCg/z4WTLPHyMqlZQqxH7I5X/pMl9l4pJgmE2zxmWOuR6, with debug_info, not stripped
gatewayapi-plugin-linux-arm64:            ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=1khFSbvEwTxvaSKR3Fda/a3QqGzCI_mM8kWyjxpCg/z4WTLPHyMqlZQqxH7I5X/pMl9l4pJgmE2zxmWOuR6, with debug_info, not stripped
```

**Comment by Philipp-Plotnikov** [comment]
Try to delete this helm chart and install it again to be sure this problem is not related with second option from the list above

**Comment by Philipp-Plotnikov** [comment]
> I'm now seeing that both `dist` builds for linux appear to be ARM if I'm reading this right
> 
> 
> 
> ```
> 
> gatewayapi-plugin-linux-amd64:            ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=1khFSbvEwTxvaSKR3Fda/a3QqGzCI_mM8kWyjxpCg/z4WTLPHyMqlZQqxH7I5X/pMl9l4pJgmE2zxmWOuR6, with debug_info, not stripped
> 
> gatewayapi-plugin-linux-arm64:            ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=1khFSbvEwTxvaSKR3Fda/a3QqGzCI_mM8kWyjxpCg/z4WTLPHyMqlZQqxH7I5X/pMl9l4pJgmE2zxmWOuR6, with debug_info, not stripped
> 
> ```

One for amd
One for arm

**Comment by FredrikAugust** [comment]
I tried `diff`ing the two versions and they seem to be identical. I'm building on an ARM mac, so I'm wondering if the GOARCH might default to `arm64` in the `make` recipe, and thus produces _two_ ARM builds.

**Comment by FredrikAugust** [comment]
I just tried to set `GOARCH=amd64` explicitly now, and it seems to create two different files, and now `file <file>` seems to reflect that:

```
gatewayapi-plugin-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=x1OlSwNtTFCJ7LkjL7yB/dHQMalkIyRzOLn2z71KH/mfhjo9aI_f5sHJRnG0Fq/uEqdhtlsLicxCFmxudLb, with debug_info, not stripped
gatewayapi-plugin-linux-arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=xCS8rb6JhpfuixUYbpPY/9uSVsG-kz6QvOR2E7DUR/z4WTLPHyMqlZQqxH7I5X/kW93zDIx7qC6AXZlWEhI, with debug_info, not stripped
```

**Comment by Philipp-Plotnikov** [comment]
Hmmm yep, I think you are right. Try to add GOARCH=amd64

**Comment by Philipp-Plotnikov** [comment]
@FredrikAugust it will be great ! I will approve
