### ISSUE TITLE
Gateway in a pending state - Kong Ingress Controller

### ISSUE THREAD

**Issue by ksgnextuple** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#49]
Kong Ingress Controller -> 3.11

The Gateway is in a pending state -> Waiting for controller. Have followed the same steps as defined in the examples.

**Comment by ksgnextuple** [comment]
Think the above is resolved, but do have one issue -> failed to get traffic router plugin argoproj-labs/gatewayAPI: unable to start plugin system: unable to find plugin (argoproj-labs/gatewayAPI): plugin argoproj-labs/gatewayAPI not configured in configmap

**Comment by Philipp-Plotnikov** [comment]
> Think the above is resolved, but do have one issue -> failed to get traffic router plugin argoproj-labs/gatewayAPI: unable to start plugin system: unable to find plugin (argoproj-labs/gatewayAPI): plugin argoproj-labs/gatewayAPI not configured in configmap
> 
> 
> 
> Any changes in the plugin name? 

Hi @ksgnextuple ! Are you sure you created ConfigMap in the right namespace, with correct name and with right structure ?
Name: argo-rollouts-config
Namespace: it should be the same as Argo Rollouts controller namespace

If it is correct, can you send the structure of ConfigMap, please ?

**Comment by ksgnextuple** [comment]
Hi @Philipp-Plotnikov, think we are good now closing the ticket. The configMap was not set properly. Could we add a pre-requisite to install the plugin through the configMap in the kong readme? Just a reminder for anyone who follows the setup.

**Comment by kostis-codefresh** [comment]
@ksgnextuple Done https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/commit/0de0634803d7698785198a28257200312e5523d4
