### ISSUE TITLE
Rollouts Delete Timeout Setting

### ISSUE THREAD

**Issue by mattbrandman** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#52]
Timeouts that are set on the HTTPRoute seem to be deleted when Argo Rollouts makes updates to the HTTPRoute. The reference for the timeouts can be found here https://gateway-api.sigs.k8s.io/api-types/httproute/#timeouts-optional. It looks like potentially in the code the timeouts are not being pulled or copied over to the new definition.

**Comment by kostis-codefresh** [comment]
Hello

Maybe create one or more Pull Requests with your changes? This way we can integrate the fix here as well.

**Comment by Philipp-Plotnikov** [comment]
Hi @mattbrandman, can you make local build and be sure that it solve your problem, please
https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/pull/50

**Comment by Philipp-Plotnikov** [comment]
@mattbrandman I merged branch to the main so you can try to make local build from main

**Comment by mattbrandman** [comment]
Great thanks! I'm currently on vacation but next week can check!

**Comment by mattbrandman** [comment]
Apologies I wasn't able to submit myself had some other things get in the way hopefully the fork was a slightly useful if messy guide

**Comment by mattbrandman** [comment]
Can confirm this fixed my issue @Philipp-Plotnikov

**Comment by mattbrandman** [comment]
Will update when a new release is cute have a 0.5.0 in the fork thats built from most recent main if you want to pull it that way as well
