### ISSUE TITLE
GRPCRoute support

### ISSUE THREAD

**Issue by VLZZZ** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#57]
Hi team!

I'm just curious if `GRPCRoute` support is on the roadmap for this plugin?

As the Gateway API is also [graduated this Route to GA starting v1.1.0](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0):
> GRPCRoute has graduated to GA (v1) and is now part of the Standard Channel.

Thank you

**Comment by Philipp-Plotnikov** [comment]
Hi @VLZZZ ! GRPCRoute is on the roadmap of plugin. We are going to implement it after e2e tests.

**Comment by Philipp-Plotnikov** [comment]
@VLZZZ What traffic provider do you use ? It supports GRPCRoute ?

**Comment by Philipp-Plotnikov** [comment]
@VLZZZ you can try to test GRPCRoute in this pr https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/pull/66
run "make gatewayapi-plugin-build" and you will get the binary

**Comment by VLZZZ** [comment]
@Philipp-Plotnikov Sorry for the delayed feedback.

We haven't tested your implementation yet and I'm not sure we'll be able to make it in the nearest weeks, but we'll do our best.

> What traffic provider do you use ? It supports GRPCRoute ?
We are using Istio in Ambient mode with `GRPCRoute` support.
