### ISSUE TITLE
Failed to run gateway-api plugin - rollouts/plugin-bin: read-only file system - with Argo Rollouts Helm chart

### ISSUE THREAD

**Issue by lolhax1337** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#61]
Argo-rollouts installed using helm chart: 
https://artifacthub.io/packages/helm/argo/argo-rollouts

After mounting new configMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config # must be so name
  namespace: argo-rollouts # must be in this namespace
data:
  trafficRouterPlugins: |-
    - name: "argoproj-labs/gatewayAPI"
      location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.2.0/gateway-api-plugin-linux-amd64"

```

And restarting deployment:
`kubectl rollout restart deployment -n argo-rollouts argo-rollouts`

New pods dont work:

```
time="2024-07-01T14:46:38Z" level=info msg="Argo Rollouts starting" version=v1.7.0+6937996
time="2024-07-01T14:46:38Z" level=info msg="Creating event broadcaster"
2024-07-01T14:46:38.975517525Z time="2024-07-01T14:46:38Z" level=info msg="Setting up event handlers"
2024-07-01T14:46:38.975524925Z time="2024-07-01T14:46:38Z" level=info msg="Setting up experiments event handlers"
2024-07-01T14:46:38.975589514Z time="2024-07-01T14:46:38Z" level=info msg="Setting up analysis event handlers"
2024-07-01T14:46:38.979223324Z time="2024-07-01T14:46:38Z" level=fatal msg="Failed to download plugins: failed to create plugin folder for plugin (argoproj-labs/gatewayAPI): (mkdir /home/argo-rollouts/plugin-bin: read-only file system)"
```

Any hint whats next?

**Comment by lolhax1337** [comment]
Looks like `emptyDir` has to be mounter under: `/home/argo-rollouts/plugin-bin` to install plugin correctly.

So docs are not valid - its impossible to install plugin only using these commands: https://rollouts-plugin-trafficrouter-gatewayapi.readthedocs.io/en/latest/installation/

Can we count on docs fix (additional commands) + fix in helm chart?

**Comment by kostis-codefresh** [comment]
Hello

The "official" way to install Argo Rollouts is via the manifest https://argo-rollouts.readthedocs.io/en/stable/installation/ 
This way is also linked from the plugin instructions

The Helm chart is unofficial and not created by the Argo team. Maybe open an issue there? https://github.com/argoproj/argo-helm

I am happy to accept any PR for the plugin docs, if you think that clarification is needed.

**Comment by lolhax1337** [comment]
Thank you, so two another things:

1. I cant push to this repo ("you dont have permissions to push to <this_repo>"), so obviously I can't make PR :(.
2. How this helm chart can be unofficial if its created by "Argo-Project" and it has "official, CNCF and verified publisher" badges? I'm asking seriously it's very confusing :) 


![image](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/assets/42574819/ed51f71f-420d-41f0-b2ba-9836beff1dba)

**Comment by kostis-codefresh** [comment]
1. You can create a PR from your own fork to this one. Fork the project first, made your edit in your own repo and then open a RP
2.  The Readme at https://github.com/argoproj/argo-helm says it is community owned. Maybe Artifact hub needs to be corrected.

![community](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/assets/39800303/c9ac1da4-e22b-4adc-a1b4-05fa0d92451e)

Anyway, it doesn't really matter. If you open a PR in the Argo-helm repo with your changes, it would be the best case anyway :-)

**Comment by kostis-codefresh** [comment]
Actually I think that artifact hub talks about the "package" (i.e. the content of the chart). The content is official, meaning that the version of Argo Rollouts mentioned is the one that matches what is published in Github.

But the chart itself is from a different team/repo https://github.com/argoproj/argo-helm
