### ISSUE TITLE
Add option of specifying which CRD version to use for Grpc

### ISSUE THREAD

**Issue by FredrikAugust** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#76]
https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/blob/43fd59f77f84c324a5d026e151136e3bdc9a90ef/pkg/plugin/grpcroute.go#L25

[Traefik helm chart now uses v1 (stable) for GRPCRoutes](https://artifacthub.io/packages/helm/traefik/traefik?modal=changelog), while this plugin uses v1alpha2. Would it be possible to add the option of specifying which version to use, or perhaps upgrade?

**Comment by kostis-codefresh** [comment]
I am in favor of upgrading but @Philipp-Plotnikov will have the final say on this.

**Comment by Philipp-Plotnikov** [comment]
We use stable channel for example for HTTPRoute.

**Comment by kostis-codefresh** [comment]
Yes. Supporting multiple versions at the same time will be super difficult in the long run (with our current team). 

This is why I suggested upgrading to latest when possible. At least as long as we release 0.x versions.

**Comment by FredrikAugust** [comment]
I'm not very familiar with versioning of the Gateway API spec (nor CRDs in general for that matter), but on the Gateway API page, [under v1, GRPCRoute is listed with `v1`](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GRPCRoute).

It also says on the [GRPCRoute page](https://gateway-api.sigs.k8s.io/api-types/grpcroute/) that it is GA in stable channel since v1.1.0.

This seems to match up with Traefik helm charts move to stable v1.1.0 ([link to line in huge diff so click at your own risk](https://github.com/traefik/traefik-helm-chart/commit/ccdb66b74d7120dd8e0dcd7300d3d3b051cea8ed#diff-0b838d08361f067cb4042dc72b273e982ee70fa0ddc232ab537b7517f241e042R4855)).

**Comment by Philipp-Plotnikov** [comment]
It seems, you are right. I will upgrade it today.

**Comment by Philipp-Plotnikov** [comment]
@FredrikAugust done

**Comment by FredrikAugust** [comment]
I don't know if this is supported yet in Linkerd, but I've created [an issue](https://github.com/linkerd/linkerd2/issues/13032). From what I can see they still use v1alpha2.
