### ISSUE TITLE
Missing Gateway API example that is userd by Linkerd

### ISSUE THREAD

**Issue by AlonGluz** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#80]
I'll be happy to contribute if this is ok with you

**Comment by kostis-codefresh** [comment]
Yes please! 

You can add it here https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples

And also update the documentation here https://rollouts-plugin-trafficrouter-gatewayapi.readthedocs.io/en/latest/provider-status/

Thank you in advance

**Comment by AlonGluz** [comment]
@kostis-codefresh On it, are there any rules I should be aware of?

**Comment by kostis-codefresh** [comment]
- Try to make it similar with the other examples
- Explain all the prerequisites needed for the setup
- Make it clear which version of LinkerD you are using and which version of the Gateway API CRDs
- Ideally it should be simple to replicate (use local cluster, an easy to find version of Linkerd, simple Argo Rollouts example) etc.

**Comment by AlonGluz** [comment]
@kostis-codefresh https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/pull/81/

**Comment by kostis-codefresh** [comment]
https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/pull/81 was merged.
