### ISSUE TITLE
Add example with header based routing

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#84]
The plugin now supports [header-based routing](https://rollouts-plugin-trafficrouter-gatewayapi.readthedocs.io/en/latest/features/header-based-routing/).

We need to create an end-to-end example with a full demo.

**Comment by AlonGluz** [comment]
@kostis-codefresh Can you assign it to me, I've got a working example I'd like to contribute

**Comment by AlonGluz** [comment]
@kostis-codefresh Where do you want this example? inside the Linkerd folder or should I create a new one l5d-header-based-routing?

**Comment by kostis-codefresh** [comment]
Yes. Add a brand new folder in the examples folder. Leave the existing linkerd example as is please

**Comment by AlonGluz** [comment]
@kostis-codefresh https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/pull/91

**Comment by AlonGluz** [comment]
@kostis-codefresh no problem, feel free to assign me with other issues, happy to contribute
